on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azureregapp.azurecr.io
        username: ${{ secrets.acr_azureregapp_username }}
        password: ${{ secrets.acr_azureregapp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t azureregapp.azurecr.io/azureakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push azureregapp.azurecr.io/azureakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azureakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azureaksclusterb852 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azureaksclusterb852`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azureaksclusterb852
        container-registry-url: azureregapp.azurecr.io
        container-registry-username: ${{ secrets.acr_azureregapp_username }}
        container-registry-password: ${{ secrets.acr_azureregapp_password }}
        secret-name: azureaksclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azureaksclusterb852
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azureregapp.azurecr.io/azureakscluster:${{ github.sha }}
        imagepullsecrets: |
          azureaksclusdockerauth
